# Generated by Django 2.2.16 on 2022-10-18 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='info_school name', max_length=30)),
                ('address', models.TextField(help_text='info_school address')),
                ('contact_number', models.CharField(help_text='school registered contact number', max_length=10)),
                ('owner_name', models.CharField(help_text='info_school owner name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student', models.ForeignKey(help_text='list of student', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(help_text='subject name to be stored', max_length=40)),
                ('standards', models.ManyToManyField(help_text='every standard subject list to be stored', to='school.Standards')),
                ('subject_teacher', models.ManyToManyField(help_text='each subject faculty name to be stored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
