# Generated by Django 2.2.16 on 2022-10-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standards',
            name='class_teacher',
            field=models.CharField(blank=True, help_text='class teacher name of that class', max_length=30, null=True),
        ),
    ]
