# Generated by Django 2.2.16 on 2022-10-19 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_standards_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standards',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='class teacher of standerd', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standards',
            name='student',
            field=models.ForeignKey(blank=True, help_text='list of student', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
