# Generated by Django 2.2.16 on 2022-10-27 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20221019_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standards',
            name='student',
        ),
    ]
