# Generated by Django 2.2.16 on 2022-10-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_standards_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailsSchool',
            new_name='SchoolDetails',
        ),
    ]
