# Generated by Django 2.2.16 on 2022-10-27 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20221027_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standards',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='class teacher of standerd', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
