# Generated by Django 2.2.16 on 2022-10-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Gender',
            new_name='gender',
        ),
    ]
