# Generated by Django 2.2.16 on 2022-11-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221019_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('faculty', 'faculty'), ('principal', 'principal')], default='faculty', max_length=20),
        ),
    ]
